### ISSUE TITLE
Comportamiento inesperado al guardar y comenzar partidas

### ISSUE THREAD

**Issue by sebastian-kupri** [julengaumard/asalto_orga_2024#1]
Cuando se inicia el programa y se intenta cargar la última partida, se carga una partida completamente nueva

Por otro lado, cuando se guarda una partida y se vuelve al menú principal, si se intenta iniciar una partida nueva se va a cargar los datos de la última partida guardada

**Comment by Valudiaz78** [comment]
Creo que ahi está resuelto
